packages:
  - contracts/*
  - packages/*
  - adapters/*

preferWorkspacePackages: true

overrides:
  "@midnight-ntwrk/compact-runtime": 0.16.0
  "@midnight-ntwrk/credential-compact": 0.2.0
  "@midnight-ntwrk/credential-did-midnight": 0.2.0
  "@midnight-ntwrk/midnight-did": 0.7.0
  "@midnight-ntwrk/midnight-did-contract": 0.7.0
  "@midnight-ntwrk/midnight-did-domain": 0.7.0
  "@midnight-ntwrk/midnight-did-jubjub-schnorr": 0.7.0
  "vitest>vite": 7.3.6
  "esbuild@>=0.27.3 <0.28.1": 0.28.1
  postcss: 8.5.23
  js-yaml: 4.3.2
  "brace-expansion@<5.0.12": 5.0.12
  "nanoid@<3.3.18": 3.3.18
  "source-map-js@<1.2.2": 1.2.2
